
// File
	X(A_FILE_INFO),
		X(A_INFO_EDIT),
	X(A_FILE_SHOWDIR),
	X(A_FILE_DEL),
	X(A_SETTINGS_SHOW),
		X(A_SETTINGS_APPLY),
	X(A_QUIT),

// List
	X(A_LIST_CHANGE),
	X(A_LIST_NEW),
	X(A_LIST_CLOSE),
	X(A_LIST_ADD_FILE),
	X(A_LIST_ADD),
		X(A_LISTADD_ADD),
	X(A_LIST_ADDTONEXT),
	X(A_LIST_FILTER),
		X(A_LISTFILTER_SET),
		X(A_LISTFILTER_CLOSE),
	X(A_LIST_SAVE),
	X(A_LIST_REMOVE),
	X(A_LIST_CLEAR),
	X(A_LIST_SORT),
	X(A_LIST_SHUFFLE),
	X(A_LIST_SCROLL_TO_CUR),
	X(A_LIST_AUTOSELECT),

// Playback
	X(A_PLAY),
	X(A_PLAYPAUSE),
	X(A_STOP),
	X(A_NEXT),
	X(A_PREV),

	X(A_SEEK),
	X(A_STEP_FWD),
	X(A_STEP_BACK),
	X(A_LEAP_FWD),
	X(A_LEAP_BACK),
	X(A_MARKER_SET),
	X(A_MARKER_JUMP),
	X(A_GOTO_SHOW),
		X(A_GOTO),

	X(A_REPEAT_TOGGLE),
	X(A_RANDOM_TOGGLE),

	X(A_VOL),
	X(A_VOLUP),
	X(A_VOLDOWN),

// Record
	X(A_RECORD_SHOW),
	X(A_RECORD_START_STOP),

// Convert
	X(A_CONVERT_SHOW),
		X(A_CONVERT_START),
	X(A_CONVERT_POS_START),
	X(A_CONVERT_POS_END),

// Help
	X(A_ABOUT_THEME_SWITCH),
	X(A_ABOUT_SHOW),
	X(A_ABOUT_HOMEPAGE),
