# phiola v2.8 GUI 日本語

MNPhiola				"phiola"

MMFile					"ファイル(&F)"
	MFInfo					"ファイル情報(&I)"
		FIMFile					"ファイル"
			FIMFKeepDate			"元のファイル日付を保持"
			FIMFWriteTagsToFile		"タグをファイルに書き込む!"
		FIMAddTag				"タグを追加"
			TAArtist				"アーティスト"
			TATitle					"タイトル"
		FIName					"名前"
		FIValue					"値"
	MFShowDir				"フォルダーを表示(&W)"
	MFRename				"名前の変更(&R)..."
		RNRenameTitle			"名前の変更"
		RNRename				"名前の変更"
	MFDelete				"削除 (ごみ箱)(&D)"
	MFMLib					"Music Library(&L)"
	MHSettings				"設定(&S)"
		STSettings				"設定"
		STTheme					"UI テーマ (再起動後に適用)"
		STPlayDev				"再生デバイス:"
		STSeekBy				"シーク幅 (秒):"
		STLeapBy				"ジャンプ幅 (秒):"
		STAutoSkip				"各トラックの先頭を自動スキップ (% または秒):"
		STAutoSkipTail			"各トラックの終端を自動スキップ (% または秒):"
		STRGNorm				"ReplayGain ノーマライザー"
		STAutoNorm				"自動ラウドネスノーマライザー"
		STEQ					"イコライザー"
			STEQFreq				"周波数 (Hz):"
			STEQWidth				"幅 (Q):"
			STEQGain				"ゲイン (dB):"
		STMLibDirs				"Music Library ディレクトリ (セミコロン区切り):"
			MLTitle					"Music Library"
			MLCPlaylist				"プレイリスト"
	MFMinimizetoTray		"トレイに最小化(&M)"
	MFExit					"終了(&X)"

MMList					"リスト(&L)"
	MLNew					"新しいタブ(&N)"
	MLClose					"タブを閉じる(&C)"
	MLAddFile				"ファイルを追加(&A)..."
	MLAdd					"追加..."
		LAListAdd				"リストに追加"
		LAAdd					"追加"
		LAName					"ファイルパスまたはURL:"
	MLAddToNextList			"次のプレイリストに追加(&D)"
	MLFilter				"フィルター(&F)..."
		LFListFilter			"フィルター"
	MLSave					"プレイリストを保存(&S)..."
	MLMetaRead				"メタデータを読み込む(&M)"
	MLRemove				"削除(&R)"
	MLRemoveNonExisting		"存在しないファイルを削除(&X)"
	MLClear					"クリア(&L)"
	MLSort					"並べ替え(&S)"
		MLSortFileName			"ファイル名で並べ替え(&N)"
		MLSortFileSize			"ファイルサイズで並べ替え(&S)"
		MLSortFileDate			"ファイル日付で並べ替え(&D)"
		MLSortTagArtist			"タグのアーティストで並べ替え(&A)"
		MLSortTagDate			"タグの日付で並べ替え(&T)"
		MLShuffle				"シャッフル(&H)"
	MLScrollToCurrent		"現在の位置にスクロール(&S)"
	MLAutoSelect			"現在の項目を自動選択 : On/Off(&A)"

MMPlayback				"再生(&P)"
	MPPlayPause				"再生/一時停止(&P)"
	MPStop					"停止(&S)"
	MPNext					"次へ(&N)"
	MPPrevious				"前へ(&R)"
	MPSeekForward			"前方にシーク(&F)"
	MPSeekBack				"後方にシーク(&B)"
	MPLeapForward			"前方にジャンプ"
	MPLeapBack				"後方にジャンプ"
	MPGoTo					"移動..."
		GTGoTo					"移動"
		GTGo					"移動!"
	MPSetMarker				"マーカーを設定"
	MPJumpToMarker			"マーカーへジャンプ"
	MPRepeat				"リピート : すべて/なし(&R)"
	MPRandom				"ランダム : On/Off(&R)"
	MPVolumeUp				"音量を上げる(&U)"
	MPVolumeDown			"音量を下げる(&D)"

MMRecord				"録音(&R)"
	MRShowRecording			"録音(&E)..."
		RCRecord				"録音"
		RCDevice				"デバイス :"
		RCLoopback				"ループバックモード ('what you hear') (WASAPI)"
		RCExclusive				"デバイスを排他モードで開く (WASAPI)"
		RCChannels				"チャンネル数 :"
		RCSampleRate			"サンプルレート (Hz):"
		RCUntil					"自動停止までの時間 ([[HH:]MM:]SS[.MSC]):"
		RCStart					"録音を開始"
	MRStartStopRec			"録音の開始/停止(&R)"

MMConvert				"変換(&C)"
	MCConvert				"変換(&C)..."
		CVConvert				"変換"
		CVOutDir				"出力フォルダー :"
		CVOutName				"出力ファイル名 :"
		CVOutExt				"出力ファイルの拡張子 :"
		CVOutChoose				"出力ファイルを選択..."
		CVFrom					"開始位置 :"
		CVUntil					"終了位置 :"
		CVTags					"タグ (NAME=VALUE;...):"
		CVCopy					"[.mp3,.m4a,.ogg] ストリームコピー"
		CVAACQ					"[.m4a] AAC 品質 : 1..5 (VBR) または 8..800 (CBR, kbit/s)"
		CVVorbisQ				"[.ogg] Vorbis 品質 : 0..10"
		CVOpusQ					"[.opus] Opus ビットレート (VBR): 6..510"
		CVMP3Q					"[.mp3] MP3 ビットレート (VBR): 9..0 または 64..320 (CBR, kbit/s)"
		CVKeepDate				"元のファイル日付を保持"
		CVOverwriteFile			"出力ファイルを上書き"
		CVStart					"変換を開始"
	MCSetStartPos			"「開始位置」を設定(&S)"
	MCSetEndPos				"「終了位置」を設定(&E)"

MMHelp					"ヘルプ(&H)"
	MHAbout					"バージョン情報(&A)"
		ABAbout					"phiola について"

LCArtist				"アーティスト"
LCTitle					"タイトル"
LCDuration				"再生時間"
LCInfo					"情報"
LCDate					"日付"
LCAlbum					"アルバム"
LCFilename				"ファイル名"

LGLog					"ログ"
