wmain.bgcolor			"#222222"
wmain.color				"#ffffff"
wmain.vlist.bgcolor		"#222222"
wmain.vlist.color		"#ffffff"
wmain.vlist.style		multi_select
winfo.vinfo.bgcolor		"#222222"
winfo.vinfo.color		"#ffffff"
winfo.vinfo.style		editable
