wmain.bgcolor			"#222222"
wmain.color				"#bb88ff"
wmain.vlist.bgcolor		"#222222"
wmain.vlist.color		"#bb88ff"
wmain.vlist.style		multi_select
winfo.vinfo.bgcolor		"#222222"
winfo.vinfo.color		"#bb88ff"
winfo.vinfo.style		editable
