-keep class com.github.stsaz.phiola.Phiola {*;}
-keep interface com.github.stsaz.phiola.Phiola$Callback {*;}
-keep class com.github.stsaz.phiola.Phiola$ConvertParams {*;}
-keep interface com.github.stsaz.phiola.Phiola$ConvertCallback {*;}
